In [1]:
import numpy as np

In [2]:
a=np.ones((3,3))

In [4]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [6]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [9]:
b=np.zeros((3,3))

In [7]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [14]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [15]:
a.shape

(6,)

In [16]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [18]:
np.sum(a)

21

In [19]:
np.max(a)

6

In [21]:
a=np.random.randint(1,100,size=(6,6))

In [22]:
np.sum(a,axis=0)

array([237, 344, 368, 142, 148, 298])

In [24]:
np.sum(a)

1537

# **Broadcasting**

In [28]:
a=np.array([1,2,3,4,5])

In [25]:
b=np.array([3,4,5,3,5])

In [29]:
a+b

array([ 4,  6,  8,  7, 10])

In [30]:
a=np.array([[1,2,3],[4,3,2]])

In [31]:
b=np.array([1,2,3])

In [32]:
a+b

array([[2, 4, 6],
       [5, 5, 5]])